### ISSUE TITLE
Can i create link with get data using DataEdit?

### ISSUE THREAD

**Issue by H0LiC** [zofe/rapyd-laravel#116]
Hi!, thanks for this plugin :).

Can i generate a link of a DataEdit with get data?, i was trying this:

$edit = DataEdit::source(new Auction());
$edit->link("auctions/participants?auction=" . Input::get('show') ,"Participants");

But the generated link was this:
<a href="http://vidalapp.com/auctions/participants" class="btn btn-default">Participants</a>

without ?auction=1

I will be glad any help.

**Comment by zofe** [comment]
because link method need to manage query string, so it ignore the QS part:
https://github.com/zofe/rapyd-laravel/blob/master/src/Zofe/Rapyd/Widget.php#L76

The "Persistence"  class try to match the url you give searching in the history  to find  old QS params,
this is needed for example  to navigate in your rapyd backend and rebuild filters, paginations, It's really useful. 

I think we can fix  your need re-adding  your custom QS  after of Persistence::get(),  
but you should  also think to change your route in "auctions/participants/{auction}"  to make a master detail  crud.

**Comment by H0LiC** [comment]
yep i thought in change the route but i realized i could not get the {auction_id} from Input::get or Input::post, so i created the link in the view, not in the DataEdit form.

I don't know if re-adding my custom QS would be necessary, if it wasn't designed to do that is better to keep it as it is.

Thanks!.

**Comment by larylinz** [comment]
Hi Zofe,  would this be it?
Line 78-80 within widget.php:
       if ((Request::path()!= $match_url) &&  (parse_url($url, PHP_URL_QUERY) == '')) {
            $url = Persistence::get($match_url);
        }

**Comment by zofe** [comment]
@larylinz seems a good fix, another one can be "merge"  new with old qs params.
I'll make some test asap

**Comment by HassanKanj** [comment]
Hi @zofe , are you thinking to add this feature in the near future or will it break the code? this will provide the tool with more flexibility if it is doable without causing other issues.

**Comment by zofe** [comment]
on L5  is patched  I think:  https://github.com/zofe/rapyd-laravel/commit/7cf227b16fca8b69c0a793b9eb92ad6bc85ea6be
on L4  I'll fix asap

**Comment by HassanKanj** [comment]
Ok thanks, I will check it, I am using L5

**Comment by zofe** [comment]
patched
