### ISSUE TITLE
Process input value before insert

### ISSUE THREAD

**Issue by sateesh15july** [zofe/rapyd-laravel#142]
I want to modify user entered value. So please suggest how I can achieve it with DataForm and DataEdit.

Thanks

**Comment by zofe** [comment]
consider to use your entity before:

to do stuff on a specific attribute you can use mutators,
http://laravel.com/docs/5.0/eloquent#accessors-and-mutators

to do general purpose stuffs on a specific event you can use events,
http://laravel.com/docs/5.0/eloquent#model-events

then if you need to manage a value in a DF or a DE,  you can use  "passed" or "saved" closure, in this case you can only "overwrite" the value because the closure is executed after `model->save()`
inside the closure you can do something like:
`$form->field('fieldname')->updateValue($mycustomvalue);`

**Comment by zofe** [comment]
no feedback,  so i close this
