### ISSUE TITLE
Not work Rapyd::scripts()

### ISSUE THREAD

**Issue by AntonBenediuk** [zofe/rapyd-laravel#176]
Hi, I have problem with scripts, laravel can't found method scripts in class Rapyd. Previously it worked fine. Also does not work method back() and not found class Image. I use laravel 4, yesterday I did the update composer. Please, help me.

**Comment by zofe** [comment]
as you can see here:
https://github.com/zofe/rapyd-laravel/blob/1.3.33/src/Zofe/Rapyd/Rapyd.php#L66
on last stable release for laravel 4: ( tag 1.3.33)   the  method is still there.

this: 
https://github.com/zofe/rapyd-laravel/blob/1.3.33/src/Zofe/Rapyd/RapydServiceProvider.php#L38
also mean that you can use Rapyd::scripts()  in your views.

So, I suppose that the problem is  in your vendor dir.
- check again this https://github.com/zofe/rapyd-laravel#install-in-laravel-4-and-50
- then  try to rebuild the vendor

**Comment by AntonBenediuk** [comment]
Thank for answer. I try to install Rapyd anew, butt still have problem with class Rapyd. I not change vendor. All work fine few days ago. I dont undestand what happen. Other classes(for example DataEdit) work fine.

**Comment by zofe** [comment]
post your composer.json so we can try your configuration

**Comment by AntonBenediuk** [comment]
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
    "require": {
        "laravel/framework": "4.2.*",
        "cartalyst/sentry": "2.1.*",
        "moltin/laravel-cart": "dev-master",
        "intervention/image": "dev-master",
        "zofe/rapyd": "1.3.*"
    },
    "require-dev": {
        "way/generators": "~2.0"
    },
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "dev"
}

**Comment by zofe** [comment]
the problem is because you're using  "intervention/image": "dev-master"
but rapyd > 1.3.1 is using  "intervention/image": "2.*" itself..  
So I think that composer try to resolve the problem using a really old version of rapyd (without the intervention image dependency)

in future, you can try to find problems using this approach:
- do a: `composer show -i`  to compare current installed version of package you need..    with the last one available
- try to use the last one available  (i.e. "zofe/rapyd": "1.3.34")  and pay attention to the composer update messages.
- You're using "minimum-stability": "dev", and you're iclu  "intervention/image": "dev-master".

To solve your problem  now  you can try to use:

        "intervention/image": "2.*",
        "zofe/rapyd": "1.3.*@dev"

**Comment by AntonBenediuk** [comment]
Its work! Thanks!!!!
