### ISSUE TITLE
Datarange insertValue

### ISSUE THREAD

**Issue by LuckyBirds** [zofe/rapyd-laravel#253]
Please check  insertValue for daterange, probably it  have ho check when data load:

We have table with big data (3 years data sale department), and if i do filter, it get data from all time period.
It work around 10 seconds.
Can filter load data only for 2 weeks ?
If i do "insertValue" on filter, it only change data in datarange field.

$filter = DataFilter::source($query);
$filter->add('date','Date','daterange')->format('Y-m-d', 'en')->insertValue('2015-10-10');
$filter->submit('search');
$filter->reset('reset');
$filter->build();

**Comment by zofe** [comment]
I' really late :)  sorry,  however filter and grids works   using query string params  so  to "filter"  by default you need to change the  default link to your filtered-grid  page  using correct  query string.

Note that format is no more needed  since  (in recent versions 5.*) the config value  can handle it.
