### ISSUE TITLE
Bug after first install in Laravel 5.2

### ISSUE THREAD

**Issue by another88** [zofe/rapyd-laravel#270]
Hi, i installed rapyd by example, enable /rapyd-demo routing and get this error  http://joxi.ru/4vAWnQ5HVl4l2W  , plz help to solve this problem.

**Comment by tacone** [comment]
Looks like you did not add the service provider.

**Comment by another88** [comment]
I'm add provider here http://joxi.ru/JMAjq8NUL8lv2e  , may be problem with assets/views publish ? but i run command "php artisan vendor:publish"

**Comment by zofe** [comment]
I see you're including the provider Illuminate\Html\HtmlServiceProvider::class  this is not loaded by default in the 5.2  and  is deprecated since the 5.0
https://laravel.com/docs/5.2/upgrade#upgrade-5.0  (see Form & HTML Helpers)

Development is moved to "Collective"  and recently rapyd moved dependencies to Collective https://laravelcollective.com/  as laravel suggested.

Try to comment out Illuminate\Html\HtmlServiceProvider::class, and if you use alias for Form and Html be sure to use correct reference:
https://laravelcollective.com/docs/5.2/html

**Comment by zofe** [comment]
I'm sing rapyd on the 5.2 and seems to work
