### ISSUE TITLE
Order grid by relationship, is it possible?

### ISSUE THREAD

**Issue by gijskooij** [zofe/rapyd-laravel#278]
With the grid, ordering is really simple with: 
$grid->add('mytitle', 'Title', true); 

But when i have a relationship like this:
$grid->add('relationship.mytitle', 'Title', true); 

I'm getting an error.
Is it possible atm or is there a workaround?

Column not found: 1054 Unknown column 'relationship.mytitle' in 'order clause'

**Comment by RichardLindhout** [comment]
I use Laravelpanel which is based on rapyd so the code markup could be a little bit different $filter instead of $this->filter.
    
$this->filter = \DataFilter::source(\DB::table('tire')
            ->leftJoin('brand', 'brand.id', '=', 'tire.brand_id')
            ->leftJoin('brand_type', 'brand_type.id', '=', 'tire.brand_type_id')
            ->leftJoin('season', 'season.id', '=', 'tire.season_id')

            ->select('tire.*','brand.name as brand_name', 'brand_type.name as brand_type_name','season.name as season_name')

            );

     
Next you put this: (and instead of $this->grid do $grid->)

     
        $this->grid->add('brand_name','Merk',true);
        $this->grid->add('brand_type_name','Model',true);
        $this->grid->add('season_name','Seizoen',true);

**Comment by gijskooij** [comment]
Hey Richard, Bedankt for the explanation.
 
This makes sense and I was expecting for some magic from Rapyd.

If this is the way to go I accept your answer.

Thanks for taking the time to comment.

**Comment by RichardLindhout** [comment]
It could be in your case that a different solution works.

I use this solution because I have the same columns everywhere so the conflict.
https://github.com/zofe/rapyd-laravel/issues/14

However, it could be that just this work in your case.

\DataGrid::source(Model::with('relationship'));

and

$grid->add('relationship.mytitle', 'Title', true);

See this issue: https://github.com/zofe/rapyd-laravel/issues/35
